language: c++
matrix:
  include:
    - os: linux
      dist: xenial
      env: QTROOT="-DQTROOT=/opt/qt59"
    - os: osx
addons:
  apt:
    sources:
      - sourceline: 'ppa:beineri/opt-qt595-xenial'
      - sourceline: 'ppa:mc3man/mpv-tests'
    packages:
      - autoconf
      - automake
      - libtool
      - libharfbuzz-dev
      - libfreetype6-dev
      - libfontconfig1-dev
      - libx11-dev
      - libxrandr-dev
      - libvdpau-dev
      - libva-dev
      - mesa-common-dev
      - libegl1-mesa-dev
      - yasm
      - libasound2-dev
      - libpulse-dev
      - libuchardet-dev
      - zlib1g-dev
      - libfribidi-dev
      - git
      - libgnutls-dev
      - libgl1-mesa-dev
      - libsdl2-dev
      - cmake
      - ninja-build
      - ca-certificates
      - qt59-meta-minimal
      - qt59webchannel
      - qt59webengine
      - qt59x11extras
      - libmpv-dev
  homebrew:
    brewfile: true
script: mkdir build && pushd build && cmake -GNinja $QTROOT -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=output .. && ninja
